const content = {
  ENGLISH: {
    FLAG: '🇵🇭',
    HEADERTITLE: 'Tadlac Lake',
    LOADING: 'Loading...',
    FORECASTDAYTITLE: 'Forecast of the day',
    FORECASTWEEKTITLE: 'Forecast of the week',
    DETAILSTITLE: 'Details',
    OVERVIEWTITLE: 'Overview',
    TEMPERATURE: 'Temperature',
    PH: 'pH',
    AMMONIUM: 'Ammonium',
    SALINITY: 'Salinity',
    NITRATE: 'Nitrate',
    CHLORIDE: 'Chloride',
    TEMPLVL1: 'The water is cold today',
    TEMPLVL2: 'The water is temperate today',
    TEMPLVL3: 'The water is hot today',
    PHLVL1: 'The water is acidic',
    PHLVL2: 'pH level is just right for fish and aquatic organisms',
    PHLVL3: 'The water is too pure',
    SALLVL1: 'The water is fresh',
    SALLVL2: 'The water has marginal salinity',
    SALLVL3: 'The water is salty',
    'NH4+LVL1': 'The water contains low levels of ammonium',
    'NH4+LVL2': 'The water contains acceptable levels of ammonium',
    'NH4+LVL3': 'The water contains elevated levels of ammonium',
    'NO3-LVL1': 'The water contains low levels of nitrate',
    'NO3-LVL2': 'The water contains acceptable levels of nitrate',
    'NO3-LVL3': 'The water contains elevated levels of nitrate',
    'Cl-LVL1': 'The water contains low levels of chloride',
    'Cl-LVL2': 'The water contains acceptable levels of chloride',
    'Cl-LVL3': 'The water contains elevated levels of chloride',
    AREA: 'Area',
    MONTHS: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'June',
      'July',
      'Aug',
      'Sept',
      'Oct',
      'Nov',
      'Dec',
    ],
    WEEKS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  FILIPINO: {
    FLAG: '🇬🇧',
    HEADERTITLE: 'Lawa ng Tadlac',
    LOADING: 'Nag lo-load...',
    FORECASTDAYTITLE: 'Panukala ngayong araw',
    FORECASTWEEKTITLE: 'Panukala ngayong linggo',
    DETAILSTITLE: 'Mga detalye',
    OVERVIEWTITLE: 'Buod',
    TEMPERATURE: 'Temperatura',
    PH: 'pH',
    AMMONIUM: 'Ammonium',
    SALINITY: 'Kaasinan',
    NITRATE: 'Nitrayd',
    CHLORIDE: 'Klorido',
    TEMPLVL1: 'Malamig ang tubig ngayon',
    TEMPLVL2: 'Katamtaman ang init ng tubig ngayon',
    TEMPLVL3: 'Mainit ang tubig ngayon',
    PHLVL1: 'Maasido ang tubig',
    PHLVL2: 'Sakto ang antas ng pH para sa mga isda at mga organismo sa tubig',
    PHLVL3: 'Masyadong puro ang tubig',
    SALLVL1: 'Sariwa ang tubig',
    SALLVL2: 'Katamtaman ang alat ng tubig',
    SALLVL3: 'Maalat ang tubig',
    'NH4+LVL1': 'Ang tubig ay naglalaman ng mababang antas ng ammonium',
    'NH4+LVL2':
      'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng ammonium',
    'NH4+LVL3': 'Ang tubig ay naglalaman ng mataas na antas ng ammonium',
    'NO3-LVL1': 'Ang tubig ay naglalaman ng mababang antas ng nitrayd',
    'NO3-LVL2':
      'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng nitrayd',
    'NO3-LVL3': 'Ang tubig ay naglalaman ng mataas na antas ng nitrayd',
    'Cl-LVL1': 'Ang tubig ay naglalaman ng mababang antas ng klorido',
    'Cl-LVL2':
      'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng klorido',
    'Cl-LVL3': 'Ang tubig ay naglalaman ng mataas na antas ng klorido',
    AREA: 'Pook',
    MONTHS: [
      'Ene',
      'Peb',
      'Mar',
      'Abr',
      'May',
      'Hun',
      'Hul',
      'Ago',
      'Set',
      'Okt',
      'Nob',
      'Des',
    ],
    WEEKS: ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab'],
  },
};

export default content;
