const content = {
  ENGLISH: {
    flag: '🇵🇭',
    headerTitle: 'Tadlac Lake',
    forecastDayTitle: 'Forecast of the day',
    forecastWeekTitle: 'Forecast of the week',
    detailsTitle: 'Details',
    overviewTitle: 'Overview',
    temperature: 'Temperature',
    pH: 'pH',
    ammonium: 'Ammonium',
    salinity: 'Salinity',
    nitrate: 'Nitrate',
    chloride: 'Chloride',
    tempLvl1: 'The water is cold today',
    tempLvl2: 'The water is temperate today',
    tempLvl3: 'The water is hot today',
    pHLvl1: 'The water is acidic',
    pHLvl2: 'pH level is just right for fish and aquatic organisms',
    pHLvl3: 'The water is too pure',
    salLvl1: 'The water is fresh',
    salLvl2: 'The water has marginal salinity',
    salLvl3: 'The water is salty',
    ammLvl1: 'The water contains low levels of ammonium',
    ammLvl2: 'The water contains acceptable levels of ammonium',
    ammLvl3: 'The water contains elevated levels of ammonium',
    nitLvl1: 'The water contains low levels of nitrate',
    nitLvl2: 'The water contains acceptable levels of nitrate',
    nitLvl3: 'The water contains elevated levels of nitrate',
    chlLvl1: 'The water contains low levels of chloride',
    chlLvl2: 'The water contains acceptable levels of chloride',
    chlLvl3: 'The water contains elevated levels of chloride',
  },
  FILIPINO: {
    flag: '🇬🇧',
    headerTitle: 'Lawa ng Tadlac',
    forecastDayTitle: 'Panukala ngayong araw',
    forecastWeekTitle: 'Panukala ngayong linggo',
    detailsTitle: 'Mga detalye',
    overviewTitle: 'Buod',
    temperature: 'Temperatura',
    pH: 'pH',
    ammonium: 'Ammonium',
    salinity: 'Kaasinan',
    nitrate: 'Nitrayd',
    chloride: 'Klorido',
    tempLvl1: 'Malamig ang tubig ngayon',
    tempLvl2: 'Katamtaman ang init ng tubig ngayon',
    tempLvl3: 'Mainit ang tubig ngayon',
    pHLvl1: 'Maasido ang tubig',
    pHLvl2: 'Sakto ang antas ng pH para sa mga isda at mga organismo sa tubig',
    pHLvl3: 'Masyadong puro ang tubig',
    salLvl1: 'Sariwa ang tubig',
    salLvl2: 'Katamtaman ang alat ng tubig',
    salLvl3: 'Maalat ang tubig',
    ammLvl1: 'Ang tubig ay naglalaman ng mababang antas ng ammonium',
    ammLvl2:
      'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng ammonium',
    ammLvl3: 'Ang tubig ay naglalaman ng mataas na antas ng ammonium',
    nitLvl1: 'Ang tubig ay naglalaman ng mababang antas ng nitrayd',
    nitLvl2: 'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng nitrayd',
    nitLvl3: 'Ang tubig ay naglalaman ng mataas na antas ng nitrayd',
    chlLvl1: 'Ang tubig ay naglalaman ng mababang antas ng klorido',
    chlLvl2: 'Ang tubig ay naglalaman ng katanggap-tanggap na antas ng klorido',
    chlLvl3: 'Ang tubig ay naglalaman ng mataas na antas ng klorido',
  },
};

export default content;
