const content = {
  ENGLISH: {
    flag: '🇵🇭',
    headerTitle: 'Tadlac Lake',
    forecastDayTitle: 'Forecast of the day',
    forecastWeekTitle: 'Forecast of the week',
    detailsTitle: 'Details',
    overviewTitle: 'Overview',
    temperature: 'Temperature',
    pH: 'pH',
    ammonium: 'Ammonium',
    salinity: 'Salinity',
    nitrate: 'Nitrate',
    chloride: 'Chloride',
    tempLvl1: 'The water is cold today',
    tempLvl2: 'The water is temperate today',
    tempLvl3: 'The water is hot today',
    pHLvl1: 'The water is acidic. Fish population may decline',
    pHLvl2: 'pH level is just right for fish and aquatic organisms',
    pHLvl3: 'The water is too pure. Aquatic organisms may die',
  },
  FILIPINO: {
    flag: '🇬🇧',
    headerTitle: 'Lawa ng Tadlac',
    forecastDayTitle: 'Panukala ngayong araw',
    forecastWeekTitle: 'Panukala ngayong linggo',
    detailsTitle: 'Mga detalye',
    overviewTitle: 'Buod',
    temperature: 'Temperatura',
    pH: 'pH',
    ammonium: 'Ammonium',
    salinity: 'Kaasinan',
    nitrate: 'Nitrayd',
    chloride: 'Klorido',
    tempLvl1: 'Malamig ang tubig ngayon',
    tempLvl2: 'Katamtaman ang init ng tubig ngayon',
    tempLvl3: 'Mainit ang tubig ngayon',
    pHLvl1: 'Maasido ang tubig. Maaring lumiit ang populasyon ng isda',
    pHLvl2: 'Sakto ang antas ng pH para sa mga isda at mga organismo sa tubig',
    pHLvl3:
      'Masyadong puro ang tubig. Maaring mamatay ang mga organismo sa tubig',
  },
};

export default content;
